# Generated by Django 5.2.5 on 2025-10-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('siembra', models.CharField(max_length=100)),
                ('cosecha', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerimientos', models.TextField()),
                ('cuidados', models.TextField()),
                ('fertilizantes_recomendados', models.TextField()),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='cultivos.cultivo')),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='plagas',
            field=models.ManyToManyField(blank=True, related_name='cultivos', to='cultivos.plaga'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivos', to='cultivos.zona'),
        ),
    ]
